#!/usr/bin/env python

import click
import api
from pegase_ref_client.apis import StructureApi


__client = StructureApi(
    api.get_client(api.REF_API, "identifiant", "mdp")
)


@click.group()
def structure():
    pass


@click.command()
@click.argument("etablissement")
def lire(etablissement):
    structure = __client.lire(etablissement, _check_return_type=False)
    click.echo(structure)


@click.command()
def liste():
    structures = __client.lire_liste(_check_return_type=False)
    click.echo(structures)


structure.add_command(lire)
structure.add_command(liste)

if __name__ == '__main__':
    structure()
